from pathlib import Path

from scripts.check_repository import collect_findings

REQUIRED_FILES = (
    "CITATION.cff",
    "CODE_OF_CONDUCT.md",
    "CONTRIBUTING.md",
    "CONTRIBUTORS.md",
    "LICENSE",
    "MAINTAINERS.md",
    "ROADMAP.md",
    "SECURITY.md",
    "THIRD_PARTY_NOTICES.md",
    "examples/PROVENANCE.md",
    "docs/assets/data/asset-provenance.yml",
    "src/openwfn/assets/3Dmol-min.js.LICENSE.txt",
)


def repository_fixture(tmp_path: Path) -> Path:
    root = tmp_path / "repository"
    root.mkdir()
    (root / "pyproject.toml").write_text(
        '[project]\nname = "openwfn"\nversion = "0.8.0a2"\n', encoding="utf-8"
    )
    (root / "README.md").write_text("# openWFN\n", encoding="utf-8")
    for relative in REQUIRED_FILES:
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("record\n", encoding="utf-8")
    return root


def test_preflight_accepts_matching_editable_metadata(tmp_path: Path) -> None:
    root = repository_fixture(tmp_path)
    egg_info = root / "src" / "openwfn.egg-info"
    egg_info.mkdir()
    (egg_info / "PKG-INFO").write_text("Name: openwfn\nVersion: 0.8.0a2\n", encoding="utf-8")

    findings = collect_findings(root, editable_installs=(("0.8.0a2", root),))

    assert findings == []


def test_preflight_reports_stale_egg_info_without_deleting_it(tmp_path: Path) -> None:
    root = repository_fixture(tmp_path)
    package_info = root / "src" / "openwfn.egg-info" / "PKG-INFO"
    package_info.parent.mkdir()
    package_info.write_text("Name: openwfn\nVersion: 0.8.0a1\n", encoding="utf-8")

    findings = collect_findings(root, editable_installs=())
    message = "\n".join(findings)

    assert "expected 0.8.0a2" in message
    assert "found 0.8.0a1" in message
    assert "python -m pip install --no-build-isolation -e ." in message
    assert package_info.is_file()


def test_preflight_reports_editable_install_from_another_checkout(tmp_path: Path) -> None:
    root = repository_fixture(tmp_path)
    other = tmp_path / "other-checkout"
    other.mkdir()

    findings = collect_findings(root, editable_installs=(("0.8.0a2", other),))
    message = "\n".join(findings)

    assert str(root.resolve()) in message
    assert str(other.resolve()) in message
    assert "python -m pip install --no-build-isolation -e ." in message


def test_preflight_reports_missing_policy_and_attribution_files(tmp_path: Path) -> None:
    root = repository_fixture(tmp_path)
    (root / "SECURITY.md").unlink()
    (root / "THIRD_PARTY_NOTICES.md").unlink()

    findings = collect_findings(root, editable_installs=())

    assert "missing required file: SECURITY.md" in findings
    assert "missing required file: THIRD_PARTY_NOTICES.md" in findings


def test_preflight_rejects_internal_branding_in_tracked_public_text(tmp_path: Path) -> None:
    root = repository_fixture(tmp_path)
    internal_brand = "Co" + "dex"
    (root / "README.md").write_text(f"Generated by {internal_brand}\n", encoding="utf-8")

    findings = collect_findings(root, editable_installs=())

    assert "README.md: internal assistant branding" in findings
