from openwfn.xyz import write_xyz  # type: ignore

def test_write_xyz(tmp_path):
    atoms = [1, 8]  # H, O
    coords = [(0.0, 0.0, 0.0), (1.0, 0.0, 0.0)]

    outfile = tmp_path / "water.xyz"

    write_xyz(outfile, atoms, coords)

    # file should exist
    assert outfile.exists()

    # content check
    content = outfile.read_text()
    assert "Generated by openWFN" in content
    assert "H" in content
    assert "O" in content
