# src/openwfn/xyz.py

from pathlib import Path

from .constants import Z_TO_SYMBOL  # type: ignore


def write_xyz(
    filename: str | Path,
    atomic_numbers: list[int],
    coordinates: list[tuple[float, float, float]],
) -> None:
    symbols = [Z_TO_SYMBOL.get(Z, "X") for Z in atomic_numbers]

    with open(filename, "w") as f:
        f.write(f"{len(symbols)}\n")
        f.write("Generated by openWFN\n")
        for sym, (x, y, z) in zip(symbols, coordinates):
            f.write(f"{sym:2s} {x:12.6f} {y:12.6f} {z:12.6f}\n")
