# src/openwfn/xyz.py

from .fchk import Z_TO_SYMBOL


def write_xyz(filename, atomic_numbers, coordinates):
    symbols = [Z_TO_SYMBOL.get(Z, "X") for Z in atomic_numbers]

    with open(filename, "w") as f:
        f.write(f"{len(symbols)}\n")
        f.write("Generated by openWFN\n")
        for sym, (x, y, z) in zip(symbols, coordinates):
            f.write(f"{sym:2s} {x:12.6f} {y:12.6f} {z:12.6f}\n")
