"""Structure writers operating on the unified molecular model."""

from pathlib import Path

from .. import __version__
from ..constants import Z_TO_SYMBOL
from ..model import Molecule


def write_structure(
    molecule: Molecule,
    path: Path,
    format: str,
    overwrite: bool = False,
) -> tuple[str, ...]:
    """Write a structure and report effective charges the format cannot preserve."""

    normalized = format.lower().lstrip(".")
    if normalized not in {"xyz", "pdb", "mol", "sdf"}:
        raise ValueError(f"Unsupported structure output format: {format}")
    if path.exists() and not overwrite:
        raise FileExistsError(f"Output exists: {path}. Pass overwrite=True to replace it.")

    ghost_count = sum(atom.nuclear_charge == 0 for atom in molecule.atoms)
    altered_count = sum(
        atom.nuclear_charge is not None
        and atom.nuclear_charge > 0
        and abs(atom.nuclear_charge - atom.atomic_number) > 1e-8
        for atom in molecule.atoms
    )
    warnings: list[str] = []
    if ghost_count:
        warnings.append(
            f"{normalized.upper()} cannot preserve effective nuclear charges: "
            f"{ghost_count} ghost center(s) will look like ordinary atoms if reloaded."
        )
    if altered_count:
        warnings.append(
            f"{normalized.upper()} cannot preserve effective nuclear charges: "
            f"{altered_count} ECP/modified-charge center(s) lose their effective charge."
        )

    if normalized == "xyz":
        lines = [str(len(molecule.atoms)), "Generated by openWFN"]
        for atom in molecule.atoms:
            symbol = Z_TO_SYMBOL[atom.atomic_number]
            x, y, z = atom.coordinates
            lines.append(f"{symbol:<2} {x:.12f} {y:.12f} {z:.12f}")
    elif normalized == "pdb":
        lines = []
        for index, atom in enumerate(molecule.atoms, start=1):
            symbol = Z_TO_SYMBOL[atom.atomic_number]
            x, y, z = atom.coordinates
            lines.append(
                f"HETATM{index:5d} {symbol:>2}   MOL A   1    "
                f"{x:8.3f}{y:8.3f}{z:8.3f}  1.00  0.00          {symbol:>2}"
            )
        for bond in molecule.bonds:
            lines.append(f"CONECT{bond.atom1 + 1:5d}{bond.atom2 + 1:5d}")
        lines.append("END")
    else:
        lines = ["openWFN", f"  openWFN {__version__}", ""]
        lines.append(f"{len(molecule.atoms):3d}{len(molecule.bonds):3d}  0  0  0  0            999 V2000")
        for atom in molecule.atoms:
            symbol = Z_TO_SYMBOL[atom.atomic_number]
            x, y, z = atom.coordinates
            lines.append(f"{x:10.4f}{y:10.4f}{z:10.4f} {symbol:<3} 0  0  0  0  0  0  0  0  0  0  0  0")
        for bond in molecule.bonds:
            lines.append(f"{bond.atom1 + 1:3d}{bond.atom2 + 1:3d}{bond.order:3d}  0  0  0  0")
        lines.append("M  END")
        if normalized == "sdf":
            lines.append("$$$$")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return tuple(warnings)
