"""Standalone offline HTML workbench exporter."""

from html import escape
from pathlib import Path

from ..branding import wordmark_svg
from ..model import CalculationData
from ..results import ResultRecord
from .payload import WorkbenchPayload


def export_workbench(
    data: CalculationData,
    path: Path,
    *,
    title: str = "openWFN Molecular Workbench",
    overwrite: bool = False,
) -> Path:
    if path.exists() and not overwrite:
        raise FileExistsError(f"Output exists: {path}. Pass overwrite=True to replace it.")
    asset_path = Path(__file__).resolve().parents[1] / "assets" / "3Dmol-min.js"
    if not asset_path.exists():
        raise FileNotFoundError(f"Missing bundled viewer asset: {asset_path}")
    engine = asset_path.read_text(encoding="utf-8").replace("</script>", "<\\/script>")
    payload = WorkbenchPayload.from_calculation(data, include_fields=True).to_json().replace("<", "\\u003c")
    document = r"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>__TITLE__</title><style>
:root{color-scheme:dark;--bg:#08111f;--panel:#101c2d;--line:#26364d;--text:#e7eef8;--muted:#9db0c9;--accent:#42c8f5}
*{box-sizing:border-box}body{margin:0;font:16px/1.45 system-ui,sans-serif;background:var(--bg);color:var(--text)}
.topbar{height:64px;display:flex;align-items:center;justify-content:space-between;padding:0 20px;border-bottom:1px solid var(--line);background:#0b1626}
.brand{font-weight:750;letter-spacing:.02em}.brand svg{display:block;width:150px;height:auto}.layout{display:grid;grid-template-columns:220px minmax(320px,1fr) 300px;height:calc(100vh - 96px)}
aside{background:var(--panel);padding:16px;border-right:1px solid var(--line)}#property-panel{border-right:0;border-left:1px solid var(--line);overflow:auto}
.workspace{display:block;width:100%;padding:11px 12px;margin:4px 0;text-align:left;color:var(--text);background:transparent;border:1px solid transparent;border-radius:7px;font:inherit;cursor:pointer}
.workspace:hover,.workspace.active{background:#172941;border-color:#315071}.workspace:focus-visible{outline:3px solid var(--accent);outline-offset:2px}
#viewer{position:relative;overflow:hidden;min-width:0;width:100%;height:100%;min-height:420px}.panel-title{font-size:.8rem;text-transform:uppercase;letter-spacing:.1em;color:var(--muted)}
.property{padding:10px 0;border-bottom:1px solid var(--line)}.property strong{display:block;color:var(--muted);font-size:.85rem}.status{height:32px;padding:6px 18px;border-top:1px solid var(--line);color:var(--muted);font-size:.85rem}
.measurement-controls[hidden],.surface-controls[hidden],.vibration-controls[hidden],.excited-state-controls[hidden]{display:none}.measure-grid{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin:12px 0}.measure-button,#measurement-reset{padding:9px;border:1px solid var(--line);border-radius:6px;background:#14243a;color:var(--text);cursor:pointer}.measure-button.active{border-color:var(--accent);color:var(--accent)}.measure-button:focus-visible,#measurement-reset:focus-visible{outline:3px solid var(--accent);outline-offset:2px}.measurement-readout{min-height:2.8rem;padding:9px;margin:8px 0;background:#0b1626;border-radius:6px}
.surface-controls label,.vibration-controls label,.excited-state-controls label{display:block;margin-top:12px;color:var(--muted)}#field-select,#isovalue,#vibration-mode-select,#vibration-amplitude,#excited-state-select{width:100%;margin-top:6px}#field-select,#vibration-mode-select,#excited-state-select{padding:8px;background:#14243a;color:var(--text);border:1px solid var(--line);border-radius:6px}.legend-row{display:flex;gap:12px;margin-top:10px}.swatch{display:inline-block;width:12px;height:12px;border-radius:50%;margin-right:5px}.positive{background:#2dd4bf}.negative{background:#f472b6}
.vibration-controls,.excited-state-controls{margin-top:8px}.vibration-details,.excited-state-details{padding:9px;margin:9px 0;background:#0b1626;border-radius:6px;font-size:.88rem}.spectrum-card{margin:12px 0;padding:8px;background:#0b1626;border:1px solid var(--line);border-radius:7px}.spectrum-card h3{margin:0 0 6px;font-size:.9rem;color:var(--muted)}.spectrum-svg{display:block;width:100%;height:145px}.spectrum-axis{stroke:#6f819a;stroke-width:1}.spectrum-curve{fill:none;stroke:var(--accent);stroke-width:1.8}.spectrum-stick{stroke:#8296b2;stroke-width:1;opacity:.65;cursor:pointer}.spectrum-stick.selected{stroke:#fbbf24;stroke-width:2}.spectrum-label{fill:#9db0c9;font-size:9px}.vector-key{font-size:.82rem;color:var(--muted);margin-top:7px}.state-source-note{font-size:.82rem;color:var(--muted);margin-top:9px}
@media(max-width:850px){.layout{grid-template-columns:170px 1fr}.layout>#property-panel{display:none}}@media(max-width:600px){.layout{display:block;height:auto}#workflow-sidebar{display:flex;overflow:auto;border-right:0}.workspace{min-width:max-content}#viewer{height:65vh}.topbar{height:auto;padding:14px}.status{height:auto}}
</style></head><body><header class="topbar"><div class="brand">__BRAND__</div><div>__TITLE__</div></header>
<main class="layout"><aside id="workflow-sidebar" aria-label="Scientific workspaces"><div class="panel-title">Workspaces</div>
<button class="workspace active" data-workspace="structure">Structure</button><button class="workspace" data-workspace="orbitals">Orbitals</button><button class="workspace" data-workspace="vibrations">Vibrations</button><button class="workspace" data-workspace="excited-states">Excited States</button><button class="workspace" data-workspace="density">Density</button><button class="workspace" data-workspace="esp">ESP</button><button class="workspace" data-workspace="measurements">Measurements</button></aside>
<section id="viewer" aria-label="Three-dimensional molecule viewer"></section><aside id="property-panel"><div class="panel-title">Properties</div><div id="properties"></div>
<section id="measurement-controls" class="measurement-controls" hidden><div class="measure-grid" role="group" aria-label="Measurement type"><button class="measure-button active" data-measurement="distance">Distance</button><button class="measure-button" data-measurement="angle">Angle</button><button class="measure-button" data-measurement="dihedral">Dihedral</button><button id="measurement-reset">Reset</button></div><strong>Selected atoms</strong><div id="measurement-selection" class="measurement-readout">None</div><strong>Result</strong><div id="measurement-result" class="measurement-readout" aria-live="polite">Select two atoms</div></section>
<section id="vibration-controls" class="vibration-controls" hidden><label for="vibration-mode-select">Vibrational mode</label><select id="vibration-mode-select"></select><div id="vibration-mode-details" class="vibration-details"></div><label for="vibration-amplitude">Display amplitude: <output id="vibration-amplitude-output">1.0</output>×</label><input id="vibration-amplitude" type="range" min="0" max="4" step="0.1" value="1"><div id="normal-mode-message" class="vector-key">Normal-mode displacement vectors are displayed as arrows only; amplitude is a visualization control and does not change source values.</div><div class="spectrum-card"><h3>IR spectrum</h3><svg id="ir-spectrum-svg" class="spectrum-svg" viewBox="0 0 260 145" aria-label="IR spectrum"></svg></div><div class="spectrum-card"><h3>Raman activity spectrum</h3><svg id="raman-spectrum-svg" class="spectrum-svg" viewBox="0 0 260 145" aria-label="Raman spectrum"></svg></div></section>
<section id="excited-state-controls" class="excited-state-controls" hidden><label for="excited-state-select">Excited state</label><select id="excited-state-select"></select><div id="excited-state-details" class="excited-state-details"></div><div class="spectrum-card"><h3>UV–Vis oscillator-strength profile</h3><svg id="uvvis-spectrum-svg" class="spectrum-svg" viewBox="0 0 260 145" aria-label="UV-Vis spectrum"></svg></div><div class="state-source-note">Displayed energies, oscillator strengths, symmetry, multiplicity, and transition dipoles are source values when available. The broadened curve is visualization-only post-processing and does not alter source values.</div></section>
<section id="surface-controls" class="surface-controls" hidden><label for="field-select">Scientific field</label><select id="field-select"></select><label for="isovalue">Isovalue: <output id="isovalue-output"></output></label><input id="isovalue" type="range" min="0.001" max="0.1" step="0.001"><div id="surface-legend" class="legend-row"><span><i class="swatch positive"></i>Positive</span><span><i class="swatch negative"></i>Negative</span></div><div id="surface-metadata" class="measurement-readout"></div></section></aside></main>
<footer class="status"><span id="status-line">Offline · molecular data remains on this device · Structure workspace</span> · <a href="https://github.com/3dmol/3Dmol.js">Molecular rendering: 3Dmol.js (BSD-3-Clause)</a></footer>
<script id="openwfn-workbench" type="application/json">__PAYLOAD__</script><script>__ENGINE__</script><script>
const payload=JSON.parse(document.getElementById('openwfn-workbench').textContent);
const atoms=payload.molecule.atoms;const xyz=[String(atoms.length),'openWFN workbench',...atoms.map(a=>`${a.symbol} ${a.coordinates.join(' ')}`)].join('\n');
const viewer=$3Dmol.createViewer('viewer',{backgroundColor:'#08111f'});viewer.addModel(xyz,'xyz');viewer.setStyle({}, {stick:{radius:.16},sphere:{scale:.28}});viewer.zoomTo();viewer.render();
function markGhostCenters(){atoms.forEach((atom,index)=>{if(atom.is_ghost){viewer.setStyle({index},{sphere:{scale:.22,color:'#9db0c9',wireframe:true}});viewer.addLabel(`Ghost ${index+1}`,{position:{x:atom.coordinates[0],y:atom.coordinates[1],z:atom.coordinates[2]},backgroundColor:'#26364d',fontColor:'white'})}});viewer.render()}
markGhostCenters();
const props=document.getElementById('properties');const measurementControls=document.getElementById('measurement-controls');const surfaceControls=document.getElementById('surface-controls');const vibrationControls=document.getElementById('vibration-controls');const excitedStateControls=document.getElementById('excited-state-controls');const fieldSelect=document.getElementById('field-select');const isovalue=document.getElementById('isovalue');const vibrationModeSelect=document.getElementById('vibration-mode-select');const vibrationAmplitude=document.getElementById('vibration-amplitude');const excitedStateSelect=document.getElementById('excited-state-select');let activeWorkspace='structure';let measurementMode='distance';let measurementSelection=[];let selectionLabels=[];let selectedVibrationMode=1;let vibrationArrows=[];let selectedExcitedStateKey='';
const vibrations=payload.properties.vibrations||null;const normalModes=payload.properties.normal_modes||{available:false,modes:[]};const excitedStates=payload.properties['excited-states']||null;const uvvisSpectrum=payload.properties['uvvis-spectrum']||null;
const vibrationButton=document.querySelector('[data-workspace="vibrations"]');if(vibrationButton&&!vibrations)vibrationButton.hidden=true;const excitedButton=document.querySelector('[data-workspace="excited-states"]');if(excitedButton&&(!excitedStates||excitedStates.status==='Unavailable'))excitedButton.hidden=true;
function vector(a,b){return [a[0]-b[0],a[1]-b[1],a[2]-b[2]]}function dot(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]}function norm(a){return Math.sqrt(dot(a,a))}function cross(a,b){return [a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]]}
function calculateDistance(a,b){return norm(vector(a,b))}function calculateAngle(a,b,c){const u=vector(a,b),v=vector(c,b);return Math.acos(Math.max(-1,Math.min(1,dot(u,v)/(norm(u)*norm(v)))))*180/Math.PI}function calculateDihedral(a,b,c,d){const b0=vector(a,b),b1=vector(c,b),b2=vector(d,c),n=norm(b1),axis=b1.map(x=>x/n),v=b0.map((x,i)=>x-axis[i]*dot(b0,axis)),w=b2.map((x,i)=>x-axis[i]*dot(b2,axis));return Math.atan2(dot(cross(v,axis),w),dot(v,w))*180/Math.PI}
function resetMeasurement(){measurementSelection=[];selectionLabels.forEach(label=>viewer.removeLabel(label));selectionLabels=[];document.getElementById('measurement-selection').textContent='None';document.getElementById('measurement-result').textContent=`Select ${{distance:2,angle:3,dihedral:4}[measurementMode]} atoms`;viewer.render()}
function selectMeasurementAtom(index){if(activeWorkspace!=='measurements')return;const required={distance:2,angle:3,dihedral:4}[measurementMode];if(measurementSelection.includes(index)||measurementSelection.length>=required)return;measurementSelection.push(index);const atom=atoms[index];selectionLabels.push(viewer.addLabel(String(index+1),{position:{x:atom.coordinates[0],y:atom.coordinates[1],z:atom.coordinates[2]},backgroundColor:'#147da1',fontColor:'white'}));document.getElementById('measurement-selection').textContent=measurementSelection.map(i=>`${i+1}:${atoms[i].symbol}`).join(' → ');if(measurementSelection.length===required){const p=measurementSelection.map(i=>atoms[i].coordinates);let value,unit;if(measurementMode==='distance'){value=calculateDistance(p[0],p[1]);unit='Å'}else if(measurementMode==='angle'){value=calculateAngle(p[0],p[1],p[2]);unit='°'}else{value=calculateDihedral(p[0],p[1],p[2],p[3]);unit='°'}document.getElementById('measurement-result').textContent=`${value.toFixed(6)} ${unit}`}viewer.render()}
viewer.setClickable({},true,atom=>selectMeasurementAtom(atom.index));document.querySelectorAll('.measure-button').forEach(button=>button.addEventListener('click',()=>{measurementMode=button.dataset.measurement;document.querySelectorAll('.measure-button').forEach(b=>b.classList.toggle('active',b===button));resetMeasurement()}));document.getElementById('measurement-reset').addEventListener('click',resetMeasurement);
function renderSurface(){viewer.removeAllSurfaces();const field=payload.fields.find(item=>item.id===fieldSelect.value);if(!field){viewer.render();return}const level=Number(isovalue.value);document.getElementById('isovalue-output').textContent=level.toFixed(3);const volume=new $3Dmol.VolumeData(field.cube,'cube');viewer.addIsosurface(volume,{isoval:level,color:'#2dd4bf',opacity:.72});if(field.signed)viewer.addIsosurface(volume,{isoval:-level,color:'#f472b6',opacity:.72});document.getElementById('surface-legend').hidden=!field.signed;document.getElementById('surface-metadata').textContent=`${field.units} · spacing ${field.grid.spacing_bohr} bohr · ${field.validation_status} · ${field.status||'success'} ${(field.warnings||[]).join(' ')}`;viewer.render()}
function configureSurfaces(workspace){const fields=payload.fields.filter(field=>field.workspace===workspace);surfaceControls.hidden=fields.length===0;fieldSelect.replaceChildren(...fields.map(field=>{const option=document.createElement('option');option.value=field.id;option.textContent=field.name;return option}));if(fields.length){isovalue.value=String(fields[0].isovalue);renderSurface()}else{viewer.removeAllSurfaces();viewer.render()}}
fieldSelect.addEventListener('change',()=>{const field=payload.fields.find(item=>item.id===fieldSelect.value);if(field)isovalue.value=String(field.isovalue);renderSurface()});isovalue.addEventListener('input',renderSurface);
function selectVibrationMode(mode){selectedVibrationMode=Number(mode);vibrationModeSelect.value=String(selectedVibrationMode);renderNormalMode();document.querySelectorAll('.spectrum-stick[data-mode]').forEach(stick=>stick.classList.toggle('selected',Number(stick.dataset.mode)===selectedVibrationMode))}
function renderVibrationalSpectrum(svgId,propertyName){const svg=document.getElementById(svgId);const spectrum=payload.properties[propertyName];svg.replaceChildren();if(!spectrum||spectrum.status==='Unavailable'){const text=document.createElementNS('http://www.w3.org/2000/svg','text');text.setAttribute('x','12');text.setAttribute('y','24');text.setAttribute('class','spectrum-label');text.textContent=spectrum?.error||'Unavailable';svg.append(text);return}const x=spectrum.frequency_cm1,y=spectrum.intensity;if(!x?.length||x.length!==y?.length)return;const left=34,right=8,top=8,bottom=25,width=260,height=145,pw=width-left-right,ph=height-top-bottom,xmin=Math.min(...x),xmax=Math.max(...x),ymax=Math.max(...y,1e-12);const sx=value=>left+(value-xmin)/(xmax-xmin||1)*pw;const sy=value=>top+(ymax-value)/ymax*ph;const axisX=document.createElementNS('http://www.w3.org/2000/svg','line');axisX.setAttribute('x1',left);axisX.setAttribute('y1',top+ph);axisX.setAttribute('x2',left+pw);axisX.setAttribute('y2',top+ph);axisX.setAttribute('class','spectrum-axis');svg.append(axisX);const points=x.map((value,index)=>`${sx(value).toFixed(2)},${sy(y[index]).toFixed(2)}`).join(' ');const curve=document.createElementNS('http://www.w3.org/2000/svg','polyline');curve.setAttribute('points',points);curve.setAttribute('class','spectrum-curve');svg.append(curve);(spectrum.lines||[]).filter(line=>!line.imaginary).forEach(line=>{const strength=propertyName==='ir-spectrum'?line.intensity:line.activity;const stick=document.createElementNS('http://www.w3.org/2000/svg','line');stick.setAttribute('x1',sx(line.frequency_cm1));stick.setAttribute('x2',sx(line.frequency_cm1));stick.setAttribute('y1',top+ph);stick.setAttribute('y2',sy(strength));stick.setAttribute('class','spectrum-stick');stick.dataset.mode=String(line.mode);stick.addEventListener('click',()=>selectVibrationMode(line.mode));svg.append(stick)});const label=document.createElementNS('http://www.w3.org/2000/svg','text');label.setAttribute('x',left+pw/2);label.setAttribute('y',height-5);label.setAttribute('text-anchor','middle');label.setAttribute('class','spectrum-label');label.textContent='Wavenumber (cm⁻¹)';svg.append(label)}
function clearVibrationArrows(){vibrationArrows.forEach(shape=>viewer.removeShape(shape));vibrationArrows=[]}
function renderNormalMode(){clearVibrationArrows();if(!vibrations)return;const mode=vibrations.modes.find(item=>Number(item.mode)===selectedVibrationMode);const details=document.getElementById('vibration-mode-details');if(!mode){details.textContent='Mode unavailable';viewer.render();return}details.textContent=`Mode ${mode.mode} · ${mode.frequency_cm1} cm⁻¹${mode.imaginary?' · imaginary':''} · IR ${mode.ir_intensity_km_mol??'—'} km/mol · Raman ${mode.raman_activity_a4_amu??'—'} Å⁴/amu`;const selected=normalModes.modes?.find(item=>Number(item.mode)===selectedVibrationMode);const message=document.getElementById('normal-mode-message');if(!normalModes.available||!selected?.displacements){message.textContent=normalModes.message||'Normal-mode displacement vectors are unavailable for this source file.';viewer.render();return}message.textContent='Normal-mode displacement vectors · arrows use source Cartesian directions; amplitude is display-only.';const amplitude=Number(vibrationAmplitude.value);document.getElementById('vibration-amplitude-output').textContent=amplitude.toFixed(1);selected.displacements.forEach((displacement,index)=>{const start=atoms[index].coordinates;const end={x:start[0]+amplitude*displacement[0],y:start[1]+amplitude*displacement[1],z:start[2]+amplitude*displacement[2]};vibrationArrows.push(viewer.addArrow({start:{x:start[0],y:start[1],z:start[2]},end,color:'#42c8f5',radius:.045,radiusRatio:1.8,mid:0.78}))});viewer.render()}
function configureVibrations(){if(!vibrations)return;vibrationModeSelect.replaceChildren(...vibrations.modes.map(mode=>{const option=document.createElement('option');option.value=String(mode.mode);option.textContent=`Mode ${mode.mode} · ${mode.frequency_cm1} cm⁻¹${mode.imaginary?' (imaginary)':''}`;return option}));selectedVibrationMode=Number(vibrationModeSelect.value||vibrations.modes[0]?.mode||1);renderVibrationalSpectrum('ir-spectrum-svg','ir-spectrum');renderVibrationalSpectrum('raman-spectrum-svg','raman-spectrum');selectVibrationMode(selectedVibrationMode)}
vibrationModeSelect.addEventListener('change',()=>selectVibrationMode(vibrationModeSelect.value));vibrationAmplitude.addEventListener('input',renderNormalMode);
function excitedStateRows(){if(!excitedStates||excitedStates.status==='Unavailable')return[];return (excitedStates.jobs||[]).flatMap(job=>(job.states||[]).map(state=>({...state,job:job.job,method_family:job.method_family,method_detail:job.method_detail,source_program:job.source_program})))}
function selectExcitedState(key){selectedExcitedStateKey=String(key);excitedStateSelect.value=selectedExcitedStateKey;const [jobText,stateText]=selectedExcitedStateKey.split(':');const selected=excitedStateRows().find(item=>String(item.job)===jobText&&String(item.state)===stateText);const details=document.getElementById('excited-state-details');if(!selected){details.textContent='Excited state unavailable';return}const dipole=selected.transition_dipole?` · dipole (${selected.transition_dipole.join(', ')}) ${selected.transition_dipole_unit||''}`:'';details.textContent=`Job ${selected.job} · State ${selected.state} · ${selected.energy_ev} eV · ${selected.wavelength_nm??'—'} nm · Oscillator strength ${selected.oscillator_strength??'—'} · multiplicity ${selected.multiplicity??'—'} · symmetry ${selected.symmetry??'—'} · ${selected.method_family}${dipole}`;document.querySelectorAll('.spectrum-stick[data-state]').forEach(stick=>stick.classList.toggle('selected',String(stick.dataset.state)===String(selected.state)))}
function renderExcitedStateSpectrum(){const svg=document.getElementById('uvvis-spectrum-svg');svg.replaceChildren();const spectrum=uvvisSpectrum;if(!spectrum||spectrum.status==='Unavailable'){const text=document.createElementNS('http://www.w3.org/2000/svg','text');text.setAttribute('x','12');text.setAttribute('y','24');text.setAttribute('class','spectrum-label');text.textContent=spectrum?.error||'UV–Vis curve unavailable';svg.append(text);return}const x=spectrum.energy_ev,y=spectrum.intensity;if(!x?.length||x.length!==y?.length)return;const left=34,right=8,top=8,bottom=25,width=260,height=145,pw=width-left-right,ph=height-top-bottom,xmin=Math.min(...x),xmax=Math.max(...x),ymax=Math.max(...y,1e-12);const sx=value=>left+(value-xmin)/(xmax-xmin||1)*pw;const sy=value=>top+(ymax-value)/ymax*ph;const axisX=document.createElementNS('http://www.w3.org/2000/svg','line');axisX.setAttribute('x1',left);axisX.setAttribute('y1',top+ph);axisX.setAttribute('x2',left+pw);axisX.setAttribute('y2',top+ph);axisX.setAttribute('class','spectrum-axis');svg.append(axisX);const points=x.map((value,index)=>`${sx(value).toFixed(2)},${sy(y[index]).toFixed(2)}`).join(' ');const curve=document.createElementNS('http://www.w3.org/2000/svg','polyline');curve.setAttribute('points',points);curve.setAttribute('class','spectrum-curve');svg.append(curve);(spectrum.lines||[]).filter(line=>line.eligible&&line.oscillator_strength!==null).forEach(line=>{const stick=document.createElementNS('http://www.w3.org/2000/svg','line');stick.setAttribute('x1',sx(line.energy_ev));stick.setAttribute('x2',sx(line.energy_ev));stick.setAttribute('y1',top+ph);stick.setAttribute('y2',sy(line.oscillator_strength));stick.setAttribute('class','spectrum-stick');stick.dataset.state=String(line.state);stick.addEventListener('click',()=>{const matching=excitedStateRows().find(item=>Number(item.state)===Number(line.state));if(matching)selectExcitedState(`${matching.job}:${matching.state}`)});svg.append(stick)});const label=document.createElementNS('http://www.w3.org/2000/svg','text');label.setAttribute('x',left+pw/2);label.setAttribute('y',height-5);label.setAttribute('text-anchor','middle');label.setAttribute('class','spectrum-label');label.textContent='Excitation energy (eV)';svg.append(label)}
function configureExcitedStates(){const rows=excitedStateRows();if(!rows.length)return;excitedStateSelect.replaceChildren(...rows.map(state=>{const option=document.createElement('option');option.value=`${state.job}:${state.state}`;option.textContent=`Job ${state.job} · State ${state.state} · ${state.energy_ev} eV · f=${state.oscillator_strength??'—'}`;return option}));selectedExcitedStateKey=excitedStateSelect.value||`${rows[0].job}:${rows[0].state}`;renderExcitedStateSpectrum();selectExcitedState(selectedExcitedStateKey)}
excitedStateSelect.addEventListener('change',()=>selectExcitedState(excitedStateSelect.value));
function showWorkspace(name){activeWorkspace=name;document.querySelectorAll('.workspace').forEach(b=>b.classList.toggle('active',b.dataset.workspace===name));measurementControls.hidden=name!=='measurements';vibrationControls.hidden=name!=='vibrations';excitedStateControls.hidden=name!=='excited-states';props.hidden=name==='measurements'||name==='vibrations'||name==='excited-states'||['orbitals','density','esp'].includes(name);configureSurfaces(name);if(name!=='vibrations')clearVibrationArrows();
const source=name==='structure'?{...payload.molecule,...payload.properties.calculation}:payload.properties[name]||{status:'No embedded field'};props.replaceChildren();Object.entries(source).forEach(([key,value])=>{const row=document.createElement('div');row.className='property';const label=document.createElement('strong');label.textContent=key.replaceAll('_',' ');row.append(label,document.createTextNode(typeof value==='object'?JSON.stringify(value):String(value)));props.append(row)});if(name==='measurements')resetMeasurement();if(name==='vibrations')configureVibrations();if(name==='excited-states')configureExcitedStates();document.getElementById('status-line').textContent=`Offline · molecular data remains on this device · ${name==='excited-states'?'Excited States':name[0].toUpperCase()+name.slice(1)} workspace`}
document.querySelectorAll('.workspace').forEach(button=>button.addEventListener('click',()=>showWorkspace(button.dataset.workspace)));showWorkspace('structure');
</script></body></html>"""
    document = document.replace("__BRAND__", wordmark_svg().strip()).replace("__TITLE__", escape(title)).replace("__PAYLOAD__", payload).replace("__ENGINE__", engine)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(document, encoding="utf-8")
    return path
